### ISSUE TITLE
Upstream repo cleanup ?

### ISSUE THREAD

**Issue by lucaparisi91** [ARCHER2-HPC/archer2-spack#6]
There is a collection of random centrally installed packages . 
Should these be cleaned up ?
This is likely to cause trouble downstream for already installed packages. What are the consequences for package users ? 
What is the most efficient way to do the process cleanly ? Upstreamed repository might need to change from time to time anyway.

**Comment by welucas2** [comment]
Additional question (potentially new issue): do we want a different software installs (upstream packages) for each version of Spack installed?

**Comment by lucaparisi91** [comment]
We decided to not upstream. So no longer relevant
